before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath==0.7.1 pytest-cov==2.5.1
  - module load singularity/3.0.2
  - ln -sfn /project/BICF/BICF_Core/shared/gudmap/cookies/deriva-cookies.txt ./test_data/
  - ln -sfn /project/BICF/BICF_Core/shared/gudmap/test_data/File_Q-Y53P.zip ./test_data/

stages:
  - unit

unit:
  stage: unit
  script:
  - singularity run 'docker://bicf/bdbag:1.0' bdbag --materialize ./test_data/File_Q-Y53P.zip
  - if [ $(singularity run 'docker://bicf/bdbag:1.0' bdbag --validate completeness ./test_data/File_Q-Y53P/ 2>&1 | tail -3 | head -n 1 | cut -c 34-) != "The directory ./test_data/File_Q-Y53P is a valid bag structure" ]; then exit 21; fi;
  - if [ $(singularity run 'docker://bicf/bdbag:1.0' bdbag --validate full ./test_data/File_Q-Y53P/ 2>&1 | tail -3 | head -n 1 | cut -c 34-) != "Bag ./test_data/File_Q-Y53P is valid" ]; then exit 21; fi;
  - if [ $(md5sum test_data/File_Q-Y53P/data/assets/Study/Q-Y4H0/Experiment/Q-Y4BY/Replicate/Q-Y5F8/hMARIS_SIX2+_RiboDep#1.gene.rpkm.txt | awk '{ print $1 }') != $(cat test_data/File_Q-Y53P/data/File.csv | cut -d ',' -f10 | tail -1) ]; then exit 21; fi;
