before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath==0.7.1 pytest-cov==2.5.1
  - module load singularity/3.0.2
  - ln -sfn /project/BICF/BICF_Core/shared/gudmap/test_data/* ./test_data/

stages:
  - unit

getBag:
  stage: unit
  script:
  - ln -sf `readlink -e ./test_data/auth/credential.json` ~/.deriva/credential.json
  - singularity run 'docker://bicf/gudmaprbkfilexfer:1.1' deriva-download-cli dev.gudmap.org --catalog 2 ./workflow/conf/replicate_export_config.json . rid=16-1ZX4

getData:
  stage: unit
  script:
  - ln -sf `readlink -e ./test_data/auth/cookies.txt` ~/.bdbag/deriva-cookies.txt
  - unzip ./test_data/bagit/Replicate_16-1ZX4
  - singularity run 'docker://bicf/gudmaprbkfilexfer:1.1' sh ./workflow/scripts/bdbagFetch.sh Replicate_16-1ZX4 16-1ZX4

trimData_se:
  stage: unit
  script:
  - if [ `nproc` -gt 8 ]; then ncore=8; else ncore=`nproc`; fi
  - singularity run 'docker://bicf/trimgalore:1.1' trim_galore --gzip -q 25 --illumina --length 35 --basename 16-1ZX4 -j ${ncore} ./test_data/fastq/16-1ZX4.R1.fastq.gz

trimData_pe:
  stage: unit
  script:
  - if [ `nproc` -gt 8 ]; then ncore=8; else ncore=`nproc`; fi
  - singularity run 'docker://bicf/trimgalore:1.1' trim_galore --gzip -q 25 --illumina --length 35 --paired --basename Q-Y5JA -j ${ncore} ./test_data/fastq/Q-Y5JA.R1.fastq.gz ./test_data/fastq/Q-Y5JA.R2.fastq.gz